const Event = require("../models/Event");
const EventTask = require("../models/EventTask");

const { generateAITasks } = require("../services/aiPlannerService");

// ============================================================
// GENERATE AI TASKS
// ============================================================

const generateAITasksForEvent = async (req, res) => {
  const { eventId } = req.params;

  try {
    // ----------------------------------------------------------
    // FIND EVENT
    // ----------------------------------------------------------

    const event = await Event.findOne({
      _id: eventId,
      user: req.user._id,
    });

    if (!event) {
      return res.status(404).json({
        success: false,
        message: "Event not found.",
      });
    }

    console.log("[AI Tasks] Generating tasks for:", event.title);

    // ----------------------------------------------------------
    // GENERATE TASKS USING GEMINI
    // ----------------------------------------------------------

    const result = await generateAITasks(event);

    if (!result || !Array.isArray(result.tasks)) {
      return res.status(502).json({
        success: false,
        message: "AI returned an invalid task list.",
      });
    }

    // ----------------------------------------------------------
    // EVENT DATE
    // ----------------------------------------------------------

    const eventDate = new Date(event.eventDate);

    if (Number.isNaN(eventDate.getTime())) {
      return res.status(422).json({
        success: false,
        message: "Event has an invalid event date.",
      });
    }

    // Normalize event date to the beginning of the day.
    eventDate.setHours(0, 0, 0, 0);

    // ----------------------------------------------------------
    // VALIDATION OPTIONS
    // ----------------------------------------------------------

    const allowedPriorities = ["Low", "Medium", "High", "Critical"];

    const allowedCategories = [
      "Venue",
      "Food",
      "Decoration",
      "Entertainment",
      "Photography",
      "Guests",
      "Transportation",
      "Budget",
      "Other",
    ];

    // ----------------------------------------------------------
    // VALIDATE AND NORMALIZE TASKS
    // ----------------------------------------------------------

    const normalizedTasks = [];

    for (let index = 0; index < result.tasks.length; index++) {
      const task = result.tasks[index];

      if (!task) {
        continue;
      }

      const title = typeof task.title === "string" ? task.title.trim() : "";

      const description =
        typeof task.description === "string" ? task.description.trim() : "";

      if (!title) {
        continue;
      }

      // --------------------------------------------------------
      // DATE VALIDATION
      // --------------------------------------------------------

      if (!task.dueDate) {
        continue;
      }

      const dueDate = new Date(`${task.dueDate}T00:00:00`);

      if (Number.isNaN(dueDate.getTime())) {
        continue;
      }

      // AI tasks must not be scheduled after the event.
      if (dueDate > eventDate) {
        console.log(
          `[AI Tasks] Skipping task "${title}" because due date is after event date.`,
        );

        continue;
      }

      // --------------------------------------------------------
      // PRIORITY VALIDATION
      // --------------------------------------------------------

      const priority = allowedPriorities.includes(task.priority)
        ? task.priority
        : "Medium";

      // --------------------------------------------------------
      // CATEGORY VALIDATION
      // --------------------------------------------------------

      const category = allowedCategories.includes(task.category)
        ? task.category
        : "Other";

      // --------------------------------------------------------
      // CREATE NORMALIZED AI TASK
      // --------------------------------------------------------

      normalizedTasks.push({
        event: event._id,
        user: req.user._id,

        title,
        description,

        dueDate,

        priority,
        category,

        status: "Pending",

        // IMPORTANT:
        // This task was generated by AI.
        source: "ai",

        completedAt: null,

        order: index,
      });
    }

    // ----------------------------------------------------------
    // CHECK RESULT
    // ----------------------------------------------------------

    if (normalizedTasks.length === 0) {
      return res.status(422).json({
        success: false,
        message: "AI generated no valid event tasks.",
      });
    }

    // ----------------------------------------------------------
    // REMOVE ONLY PREVIOUS AI TASKS
    // ----------------------------------------------------------
    //
    // IMPORTANT:
    // Manual tasks are NOT deleted.
    //
    // Completed AI tasks are also preserved.
    // Cancelled AI tasks are preserved.
    //
    // Only active AI tasks are replaced.
    // ----------------------------------------------------------

    const deleteResult = await EventTask.deleteMany({
      event: event._id,
      user: req.user._id,
      source: "ai",
      status: {
        $in: ["Pending", "In Progress"],
      },
    });

    console.log(
      `[AI Tasks] Removed ${deleteResult.deletedCount} previous active AI tasks.`,
    );

    // ----------------------------------------------------------
    // SAVE NEW AI TASKS
    // ----------------------------------------------------------

    const savedTasks = await EventTask.insertMany(normalizedTasks);

    console.log(
      `[AI Tasks] ${savedTasks.length} tasks generated successfully.`,
    );

    // ----------------------------------------------------------
    // RESPONSE
    // ----------------------------------------------------------

    return res.status(200).json({
      success: true,

      message: `${savedTasks.length} AI tasks generated successfully.`,

      count: savedTasks.length,

      model: result.model,

      tasks: savedTasks,
    });
  } catch (error) {
    console.error("=============================================");
    console.error("[AI Tasks ERROR]");
    console.error("Message:", error.message);
    console.error("Status:", error.status);
    console.error("Status Code:", error.statusCode);
    console.error("Name:", error.name);
    console.error("Full Error:", error);
    console.error("=============================================");

    return res.status(error.statusCode || 500).json({
      success: false,
      message: error.message || "Failed to generate AI tasks.",
    });
  }
};

module.exports = {
  generateAITasks: generateAITasksForEvent,
};
